export enum ErrorCode {
  INVALID_URL = "E001",
  EMPTY_SELECTOR = "E002",
  INVALID_REGEX = "E003",
  EMPTY_TASK_CONFIG = "E004",

  BROWSER_LAUNCH_FAILED = "E101",
  PAGE_NAVIGATE_TIMEOUT = "E102",
  ELEMENT_NOT_FOUND = "E103",
  ACTION_OPERATION_FAILED = "E104",

  NETWORK_CAPTURE_ERROR = "E201",
  SCRIPT_EXEC_TIMEOUT = "E202",
  STORAGE_QUERY_FAILED = "E203",

  FS_MKDIR_FAILED = "E301",
  FS_WRITE_FAILED = "E302",

  UNKNOWN_ERROR = "E999",

  SESSION_EXPIRED = "E401",
  SESSION_INVALID = "E402",
}
