/* eslint-disable no-magic-numbers */

export const DEFAULT_ACTION_TIMEOUT_MS = 15000;
export const NETWORK_IDLE_WAIT_MS = 800;
export const SCRIPT_SAFE_DELAY_MS = 50;
export const MIN_REQUEST_DELAY = 80;
export const MAX_REQUEST_DELAY = 200;
export const MAX_INTERACTIVE_ELEMENT_LIMIT = 12;
export const MAX_API_LIST_LIMIT = 8;
export const COOKIE_INSECURE_SCORE_DEDUCT = 5;
export const RISK_ITEM_SCORE_DEDUCT = 8;

export const POST_NAVIGATION_IDLE_WAIT_MS = 3000;
export const LOGIN_PAGE_LOAD_TIMEOUT_MS = 30000;
export const SESSION_VALIDATE_TIMEOUT_MS = 15000;
export const MANUAL_LOGIN_TIMEOUT_MS = 5 * 60 * 1000;
export const REQUEST_CAPTURE_EXTRA_WAIT_MS = 3000;

export const LOGIN_FORM_WAIT_MS = 2000;
export const LOGIN_SUBMIT_AFTER_WAIT_MS = 1500;
export const LOGIN_MODAL_TRIGGER_WAIT_MS = 1500;
export const LOGIN_POLL_INTERVAL_MS = 500;
export const PAGE_LOAD_FALLBACK_TIMEOUT_MS = 10000;
export const PASSWORD_TAB_SWITCH_DELAY_MS = 800;
export const LOGIN_SUCCESS_POLL_MS = 2000;
export const CAPTURE_AFTER_LOGIN_WAIT_MS = 3000;

export const MAX_DISPLAY_ITEMS = 15;
export const MAX_CAPTION_LENGTH = 80;  
export const SECURITY_SCORE_HIGH = 85;
export const SECURITY_SCORE_MEDIUM = 60;
export const SECURITY_SCORE_LOW = 30;
export const SECURITY_WEIGHT_RISK = 8;
export const SECURITY_WEIGHT_COOKIE = 5;
